version: '3.0'
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 设置了 root 用户的密码为 root
      MYSQL_ROOT_PASSWORD: root

    #
    volumes:
      - ./script/mysql:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"

  redis:
    image: 'bitnami/redis:latest'
    environment:
#      我靠，这里注意- ALLOW_EMPTY_PASSWORD=yes 的=两边是不能有空格的
#      格式很重要
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'